---
sidebar: sidebar 
permalink: install-setup/cable-hardware.html 
keywords: asa r2, aff a1k, aff a70, aff a90, aff c80, asa a1k, asa a90, asa a70, asa a30, asa a20, asa a50, asa c30 cable controllers 
summary: 'Collega il tuo sistema storage ASA per abilitare la comunicazione del cluster, l"accesso alla rete host, la connettività di gestione e le connessioni agli shelf di storage.' 
---
= Collegare l'hardware per il sistema di storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Collega il tuo sistema storage ASA per abilitare la comunicazione del cluster, l'accesso alla rete host, la connettività di gestione e le connessioni agli shelf di storage.



[[overview-of-hardware-cabling]]
== Panoramica del cablaggio hardware

Il cablaggio varia a seconda del modello della piattaforma, poiché ogni modello di ASA r2 presenta posizioni degli slot, assegnazioni delle porte e configurazioni dei moduli I/O specifiche. Selezionare la procedura per il proprio modello di ASA r2:

* link:cable-hardware-a1k.html["Cavo ASA A1K"]
* link:cable-hardware-a70-90.html["Cavo ASA A70 e A90"]
* link:cable-hardware-a20-30-50.html["Cavo ASA A20, A30 e A50"]
* link:cable-hardware-c30.html["Cavo ASA C30"]


Durante il cablaggio hardware, collegherai quattro tipi di connessioni:

* *Connessioni cluster/HA*
+
Collega i due controller tra loro (cluster senza switch) o agli switch di rete del cluster (cluster con switch). Queste connessioni consentono la comunicazione del cluster e il failover ad alta disponibilità tra le coppie di controller. Il traffico di interconnessione del cluster e il traffico HA condividono le stesse porte fisiche.

* *Connessioni di rete host*
+
Collega i controller agli host SAN utilizzando Ethernet (iSCSI, NVMe/TCP) o Fibre Channel (FC, NVMe/FC) in base alla configurazione dell'host. Queste connessioni forniscono l'accesso ai dati per i carichi di lavoro di storage.

* *Connessioni di rete di gestione*
+
Collega i controller alla tua rete di gestione per accedere all'amministrazione del sistema tramite ONTAP System Manager e CLI.

* *Connessioni shelf di storage*
+
Collega i controller alle mensole di storage NS224 per fornire capacità di storage al tuo sistema.





[[additional-resources]]
== Risorse aggiuntive

Le procedure di cablaggio mostrano le configurazioni più comuni. Il cablaggio specifico dipende dai componenti ordinati per il sistema storage. Per informazioni complete sulla configurazione e la priorità degli slot, vedere link:https://hwu.netapp.com["NetApp Hardware Universe"^].
