---
sidebar: sidebar 
permalink: install-setup/deploy-hardware.html 
keywords: asa r2, install hardware, deploy hardware, aff a1k, aff a70, aff a90, aff c80, asa a1k, asa a90, asa a70, asa a30, asa a20, asa a50 
summary: 'Scopri come installare i kit guide per il sistema di storage ASA R2 e gli shelf di storage e come fissare l"hardware ASA R2 nel cabinet o nel rack per telecomunicazioni.' 
---
= Installare il sistema di storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver preparato l'installazione del sistema di archiviazione ASA R2, installare l'hardware per il sistema. Per prima cosa, montare i kit guide. Quindi, installare e proteggere il sistema di archiviazione in un cabinet o in un rack per telecomunicazioni.

.Prima di iniziare
* Assicurarsi di avere le istruzioni fornite con il kit guida.
* Prestare attenzione ai problemi di sicurezza associati al peso del sistema di stoccaggio e del ripiano di stoccaggio.
* Tenere presente che il flusso d'aria attraverso il sistema di storage entra dalla parte anteriore dove sono installati il pannello o i cappucci terminali e fuoriesce dalla parte posteriore dove si trovano le porte.


.Fasi
. Installare i kit guide per il sistema di archiviazione e gli scaffali, secondo necessità, seguendo le istruzioni fornite con i kit.
. Installare e fissare il sistema di archiviazione nell'armadietto o nel rack per telecomunicazioni:
+
.. Posizionare il sistema di stoccaggio sulle guide al centro del cabinet o del rack per telecomunicazioni, quindi sostenere il sistema di archiviazione dal basso e farlo scorrere in posizione.
.. Fissare il sistema di archiviazione all'armadietto o al rack per telecomunicazioni utilizzando le viti di montaggio incluse.


. Fissare il frontalino alla parte anteriore del sistema di archiviazione.
. Se il sistema ASA R2 viene fornito con un dispositivo di gestione dei cavi, collegarlo al retro del sistema di archiviazione.
+
image::../media/drw_affa1k_install_cable_mgmt_ieops-1697.svg[Installare il dispositivo di gestione dei cavi]

. Installare e fissare lo shelf di archiviazione:
+
.. Posizionare la parte posteriore del ripiano sulle guide, quindi sostenere il ripiano dal basso e farlo scorrere nell'armadietto o nel rack per telecomunicazioni.
+
Se si installano più shelf, posizionare il primo shelf direttamente sopra i controller. Posizionare il secondo shelf direttamente sotto i controller. Ripetere questo modello per tutti gli shelf di storage aggiuntivi.

.. Fissare il ripiano all'armadietto o al rack per telecomunicazioni utilizzando le viti di montaggio in dotazione.




.Quali sono le prossime novità?
Dopo aver installato l'hardware per il sistema ASA R2, si link:cable-hardware.html["Collega i controller e gli shelf di storage del sistema ASA R2"].
