---
sidebar: sidebar 
permalink: install-setup/install-setup-requirements.html 
keywords: asa r2, install, setup, requirements, cautions 
summary: 'Esaminare l"attrezzatura necessaria e le precauzioni di sollevamento per il sistema di storage e i ripiani di stoccaggio ASA R2.' 
---
= Requisiti di installazione per i sistemi storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esaminare l'attrezzatura necessaria e le precauzioni di sollevamento per il sistema di storage e i ripiani di stoccaggio ASA R2.



== Attrezzatura necessaria per l'installazione

Per installare il sistema di storage ASA R2 sono necessari i seguenti strumenti e attrezzature.

* Accesso a un browser Web per configurare il sistema di archiviazione
* Cinturino da scariche elettrostatiche (ESD)
* Torcia
* Computer portatile o console con connessione USB/seriale
* Graffetta o penna a sfera con punta stretta per impostare gli ID dei ripiani di conservazione
* Cacciavite Phillips n. 2




== Precauzioni per il sollevamento

I sistemi storage e gli shelf di storage ASA R2 sono pesanti. Prestare attenzione durante il sollevamento e lo spostamento di questi elementi.



=== Pesi del sistema di archiviazione

Prendere le precauzioni necessarie quando si sposta o si solleva il sistema di archiviazione ASA R2.

[role="tabbed-block"]
====
.A1K
--
Un sistema di storage ASA A1K può pesare fino a 28,5 kg (62,83 lb). Per sollevare l'impianto di stoccaggio, utilizzare due persone o un sollevatore idraulico.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[Icona di avvertenza sollevamento ASA A1K]

--
.A70 e A90
--
Un sistema storage ASA A70 o ASA A90 può pesare fino a 68,8 kg (151,68 libbre). Per sollevare l'impianto di stoccaggio, utilizzare quattro persone o un sollevatore idraulico.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[Icona di attenzione peso ASA A90 ASA A70]

--
.A20, A30 E A50
--
Un sistema storage ASA A20, ASA A30 o ASA A50 può pesare fino a 27,9 kg (61,5 libbre). Per sollevare l'impianto di stoccaggio, utilizzare due persone o un sollevatore idraulico.

image::../media/drw_g_lifting_weight_ieops-1831.svg[Icona di attenzione al peso ASA A20 A30 A50]

--
.C30
--
Un sistema di archiviazione ASA C30 può pesare fino a 61,5 libbre (27,9 kg). Per sollevare l'impianto di stoccaggio, utilizzare due persone o un sollevatore idraulico.

image::../media/drw_g_lifting_weight_ieops-1831.svg[Icona di avvertenza del peso ASA A20 A30 o A50]

--
====


=== Pesi dei ripiani

Prendere le precauzioni necessarie quando si sposta o si solleva il ripiano.

[role="tabbed-block"]
====
.NS224 ripiano
--
Un ripiano NS224 può pesare fino a 30,29 kg (66,78 lb). Per sollevare il ripiano, utilizzare due persone o un sollevatore idraulico. Tenere tutti i componenti nel ripiano (anteriore e posteriore) per evitare di sbilanciare il peso del ripiano.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 NSM100 attenzione al sollevamento]

--
.NS224 shelf con NSM100B moduli
--
Uno shelf NS224 con NSM100B moduli può pesare fino a 25,8 kg (56,8 lb). Per sollevare il ripiano, utilizzare due persone o un sollevatore idraulico. Tenere tutti i componenti nel ripiano (anteriore e posteriore) per evitare di sbilanciare il peso del ripiano.

image::../media/drw_ns224_nsm100b_lifting_weight_ieops-1832.svg[NS224 con NSM100b attenzione al sollevamento]

--
====
.Informazioni correlate
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informazioni sulla sicurezza e avvisi normativi"^]


.Quali sono le prossime novità?
Dopo aver esaminato i requisiti hardware, si link:prepare-hardware.html["Preparazione dell'installazione del sistema di storage ASA R2"].
