---
sidebar: sidebar 
permalink: install-setup/install-setup-requirements.html 
keywords: asa r2, install, setup, requirements, cautions 
summary: 'Esaminare l"attrezzatura necessaria e le precauzioni di sollevamento per il sistema di storage e i ripiani di stoccaggio ASA R2.' 
---
= Requisiti di installazione per i sistemi storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esaminare l'attrezzatura necessaria e le precauzioni di sollevamento per il sistema di storage e i ripiani di stoccaggio ASA R2.



== Attrezzatura necessaria per l'installazione

Per installare il sistema di storage ASA R2 sono necessari i seguenti strumenti e attrezzature.

* Accesso a un browser Web per configurare il sistema di archiviazione
* Cinturino da scariche elettrostatiche (ESD)
* Torcia
* Computer portatile o console con connessione USB/seriale
* Graffetta o penna a sfera con punta stretta per l'impostazione di NS224 ID scaffali
* Cacciavite Phillips n. 2




== Precauzioni per il sollevamento

I sistemi storage ASA R2 e gli shelf di storage NS224 sono pesanti. Prestare attenzione durante il sollevamento e lo spostamento di questi elementi.



=== Pesi del sistema di archiviazione

Prendere le precauzioni necessarie quando si sposta o si solleva il sistema di archiviazione ASA R2.

[role="tabbed-block"]
====
.ASA A1K
--
Un sistema di storage ASA A1K può pesare fino a 28,5 kg (62,83 lb). Per sollevare l'impianto, utilizzare due persone o un sollevatore idraulico.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[Icona di avvertenza sollevamento AFF A1K]

--
.ASA A70 e ASA A90
--
Un sistema storage ASA A70 o ASA A90 può pesare fino a 68,8 kg (151,68 libbre). Per sollevare l'impianto, utilizzare quattro persone o un sollevatore idraulico.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90]

--
====


=== Peso del ripiano

Un ripiano di stoccaggio NS224 può pesare fino a 30,29 kg (66,78 lb). Per sollevare il ripiano portaoggetti, utilizzare due persone o un sollevatore idraulico. Tenere tutti i componenti nel ripiano portaoggetti (anteriore e posteriore) per evitare di sbilanciare il peso del ripiano.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 attenzione al sollevamento]

.Informazioni correlate
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informazioni sulla sicurezza e avvisi normativi"^]


.Quali sono le prossime novità?
Dopo aver esaminato i requisiti hardware, si link:prepare-hardware.html["Preparazione dell'installazione del sistema di storage ASA R2"].
