---
sidebar: sidebar 
permalink: install-setup/set-up-data-access.html 
keywords:  
summary:  
---
= Abilitare l'accesso ai dati dagli host SAN al sistema di storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per impostare l'accesso ai dati, è necessario assicurarsi che i parametri e le impostazioni critiche sul client SAN per il corretto funzionamento con ONTAP siano configurati correttamente. Se si fornisce storage per l'ambiente VMware, è necessario installare OTV 10,3 semplicemente per la gestione dello storage ASA R2.



== Configurare l'accesso ai dati dagli host SAN

La configurazione necessaria per impostare l'accesso ai dati dal sistema ASA R2 agli host SAN varia IN base al sistema operativo host e al protocollo. La corretta configurazione è importante per ottenere le migliori performance e il successo del failover.

Consultare la documentazione dell'host SAN ONTAP per link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["Client SCSI VMware vSphere"^] link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Client VMware vSphere NVMe"^]e link:https://docs.netapp.com/us-en/ontap-sanhost/overview.html["Altri client SAN"^] per configurare correttamente gli host per la connessione al sistema ASA R2.



== Migrazione di macchine virtuali VMware

Per migrare il carico di lavoro delle macchine virtuali da un sistema storage ASA a un sistema storage ASA R2, NetApp consiglia di utilizzare link:https://www.vmware.com/products/cloud-infrastructure/vsphere/vmotion["VMware vSphere vMotion"^] per eseguire una migrazione live e senza interruzioni dei dati.



== Configura il tuo sistema ASA R2 come provider di storage nel tuo ambiente VMware

Puoi utilizzare i tool ONTAP per VMware per abilitare facilmente il tuo sistema ASA R2 come storage provider nel tuo ambiente VMware.

Strumenti ONTAP per VMware vSphere è un set di strumenti che funzionano in combinazione con VMware vCenter Server Virtual Appliance (vCSA) per una facile gestione delle macchine virtuali sugli host VMware ESXi.

I sistemi ASA R2 sono supportati da link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/concepts/ontap-tools-overview.html["Tool ONTAP per VMware vSphere 10,3"^] e versioni successive.

Scopri come link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["Implementa i tool ONTAP per VMware"^]e quindi utilizzalo per effettuare le seguenti operazioni:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["Aggiungere istanze di vCenter Server"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-esx-server-multipath-and-timeout-settings.html["Configurare le impostazioni dell'host ESXi"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/discover-storage-systems-and-hosts.html["Rilevamento del sistema di storage e degli host ASA R2"^]


.Quali sono le prossime novità?
Puoi link:../manage-data/provision-san-storage.html["provisioning dello storage"]abilitare gli host SAN a leggere e scrivere i dati nelle unità storage.
