---
sidebar: sidebar 
permalink: install-setup/set-up-data-access.html 
keywords:  
summary:  
---
= Abilitare l'accesso ai dati dagli host SAN al sistema di storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per impostare l'accesso ai dati, è necessario assicurarsi che i parametri e le impostazioni critiche sul client SAN per il corretto funzionamento con ONTAP siano configurati correttamente. Se si fornisce storage per l'ambiente VMware, è necessario installare OTV 10,3 semplicemente per la gestione dello storage ASA R2.



== Configurare l'accesso ai dati dagli host SAN

La configurazione necessaria per impostare l'accesso ai dati dal sistema ASA R2 agli host SAN varia IN base al sistema operativo host e al protocollo. La corretta configurazione è importante per ottenere le migliori performance e il successo del failover.

Consultare la documentazione dell'host SAN ONTAP per link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["Client SCSI VMware vSphere"^] link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Client VMware vSphere NVMe"^]e link:https://docs.netapp.com/us-en/ontap-sanhost/overview.html["Altri client SAN"^] per configurare correttamente gli host per la connessione al sistema ASA R2.



== Migrazione di macchine virtuali VMware

Per migrare il carico di lavoro delle macchine virtuali da un sistema storage ASA a un sistema storage ASA R2, NetApp consiglia di utilizzare link:https://www.vmware.com/products/cloud-infrastructure/vsphere/vmotion["VMware vSphere vMotion"^] per eseguire una migrazione live e senza interruzioni dei dati.



== Migrare i dati da un sistema di archiviazione di terze parti

A partire da ONTAP 9.17.1, è possibile utilizzare Foreign LUN Import (FLI) per migrare i dati da una LUN su un sistema di storage di terze parti a un sistema ASA r2. L'utilizzo di FLI per la migrazione dei dati può aiutare a ridurre il rischio di perdita di dati e tempi di inattività durante il processo di migrazione.

FLI supporta sia le migrazioni online che offline. In una migrazione online, il sistema client rimane online mentre i dati vengono copiati dal sistema di storage di terze parti al sistema di storage ONTAP . Le migrazioni online sono supportate dai sistemi operativi host Windows, Linux ed ESXi. In una migrazione offline, il sistema client viene portato offline, i dati LUN vengono copiati dal sistema di storage di terze parti al sistema di storage ONTAP e quindi il sistema client viene riportato online.

* Impara come eseguire un link:https://docs.netapp.com/us-en/ontap-fli/san-migration//concept_fli_offline_workflow.html["Migrazione offline FLI"^] .
* Impara come eseguire un link:https://docs.netapp.com/us-en/ontap-fli/san-migration//concept_fli_online_workflow.html["Migrazioni online FLI"^] .




== Configura il tuo sistema ASA R2 come provider di storage nel tuo ambiente VMware

Puoi utilizzare i tool ONTAP per VMware per abilitare facilmente il tuo sistema ASA R2 come storage provider nel tuo ambiente VMware.

Strumenti ONTAP per VMware vSphere è un set di strumenti che funzionano in combinazione con VMware vCenter Server Virtual Appliance (vCSA) per una facile gestione delle macchine virtuali sugli host VMware ESXi.

I sistemi ASA R2 sono supportati da link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/concepts/ontap-tools-overview.html["Tool ONTAP per VMware vSphere 10,3"^] e versioni successive.

Scopri come link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["Implementa i tool ONTAP per VMware"^]e quindi utilizzalo per effettuare le seguenti operazioni:

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["Aggiungere istanze di vCenter Server"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-esx-server-multipath-and-timeout-settings.html["Configurare le impostazioni dell'host ESXi"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/discover-storage-systems-and-hosts.html["Rilevamento del sistema di storage e degli host ASA R2"^]


.Quali sono le prossime novità?
Puoi link:../manage-data/provision-san-storage.html["provisioning dello storage"]abilitare gli host SAN a leggere e scrivere i dati nelle unità storage.
