---
sidebar: sidebar 
permalink: secure-data/modify-arp-snapshot-retention-period.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, ai, alerts, respond, warnings, security 
summary: Scopri come modificare i periodi di conservazione degli snapshot ARP in base alle tue esigenze aziendali e di archiviazione. 
---
= Modificare i periodi di conservazione degli snapshot ARP/AI sui sistemi di archiviazione ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se Autonomous Ransomware Protection with Artificial Intelligence (ARP/AI) rileva attività anomale su una o più unità di storage nel tuo sistema ASA r2, crea automaticamente uno snapshot ARP per proteggere i dati. A seconda della tua capacità di storage e delle esigenze aziendali, potresti voler aumentare o diminuire il periodo di conservazione predefinito degli snapshot ARP. Ad esempio, potresti aumentare il periodo di conservazione per le applicazioni business-critical per supportare finestre di recovery di dati più lunghe o diminuirlo per le applicazioni non critiche per risparmiare spazio di storage.

Il periodo di conservazione predefinito per lo snapshot ARP varia a seconda dell'azione intrapresa in risposta all'attività anomala.

[cols="2,2"]
|===
| Se intraprendi questa azione... | Per impostazione predefinita, gli snapshot ARP vengono conservati per... 


| Contrassegna come falso positivo | 12 ore 


| Contrassegna come potenziale attacco ransomware | 7 giorni 


| Non intraprendere azioni immediate | 10 giorni 
|===
Puoi modificare i periodi di conservazione predefiniti utilizzando l'interfaccia a riga di comando (CLI) di ONTAP. Vedi  https://docs.netapp.com/us-en/ontap/anti-ransomware/modify-automatic-snapshot-options-task.html["Modifica le opzioni per gli snapshot automatici ONTAP"] per i passaggi su come modificare il periodo di conservazione predefinito.
