---
sidebar: sidebar 
permalink: secure-data/pause-resume-anti-ransomware-protection.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, ai, pause, resume, suspend 
summary: Se stai pianificando un evento di carico di lavoro insolito, puoi sospendere temporaneamente ARP con analisi AI per prevenire falsi positivi nel rilevamento di attacchi ransomware 
---
= Metti in pausa o riprendi la protezione ARP/AI sui sistemi di storage ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire da ONTAP 9.17.1, puoi usare Autonomous Ransomware Protection with Artificial Intelligence (ARP/AI) per proteggere i dati sul tuo sistema ASA r2. Se stai pianificando un evento con un carico di lavoro insolito, puoi sospendere temporaneamente l'analisi ARP/AI per evitare falsi positivi. Dopo che l'evento è terminato, puoi riprendere l'analisi ARP/AI.



[[pause-arpai]]
== Pausa ARP/AI

Prima di avviare un evento di carico di lavoro insolito, potresti dover sospendere temporaneamente l'analisi ARP/AI per evitare falsi positivi.

.Fasi
. In System Manager, selezionare *Storage*.
. Seleziona le unità di archiviazione per le quali desideri mettere in pausa ARP/AI.
. Seleziona *Sospendi anti-ransomware*.


.Risultato
L'analisi ARP/AI viene sospesa per le unità di archiviazione selezionate e non ti verrà segnalata alcuna attività sospetta in System Manager finché non riprenderai ARP/AI.



[[resume-arpai]]
== Riprendi ARP/AI

Se metti in pausa ARP/AI durante un carico di lavoro insolito, riattivalo quando il carico di lavoro è terminato per proteggere i tuoi dati dagli attacchi ransomware.

.Fasi
. In System Manager, selezionare *Storage*.
. Selezionare le unità di archiviazione per le quali si desidera riprendere ARP/AI.
. Seleziona *Ripristina anti-ransomware*.


.Risultato
L'analisi dei potenziali attacchi ransomware viene ripresa e le attività sospette vengono segnalate in Gestione sistema.
