---
sidebar: sidebar 
permalink: secure-data/respond-anti-ransomware-protection-alerts.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, ai, alerts, respond, warnings, security 
summary: Visualizza gli avvisi sui potenziali attacchi ransomware e agisci in Gestione sistema. 
---
= Rispondi agli avvisi ARP/AI sui sistemi di storage ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se Autonomous Ransomware Protection with Artificial Intelligence (ARP/AI) rileva attività anomale su una o più unità di storage nel tuo sistema ASA r2, System Manager visualizza un avviso sulla dashboard. Esamina l'avviso, verifica l'attività e intervieni se necessario per proteggere i tuoi dati.

Se viene visualizzato un messaggio di avviso ARP/AI, usa l'apposito strumento di verifica dell'integrità dell'applicazione per controllare i dati sull'unità di storage prima di agire. Verificare l'integrità dei dati sull'unità di storage ti aiuta a capire se l'attività è accettabile o se si tratta di un potenziale attacco ransomware.

[cols="2,2"]
|===
| Se l'attività anomala è ... | Allora fai così... 


| Accettabile | Contrassegna l'attività come falso positivo. 


| Un potenziale attacco ransomware | Contrassegna l'attività come potenziale attacco ransomware. 


| Indeterminato | Non intraprendere azioni immediate. Monitora l'unità di archiviazione per un massimo di 7 giorni. Se l'unità di archiviazione continua a funzionare normalmente, contrassegna l'attività come falso positivo. Se l'unità di archiviazione continua a mostrare attività anomale, contrassegna l'attività come potenziale attacco ransomware. 
|===
.Fasi
. In System Manager, selezionare *Dashboard*.
+
Se ARP/AI ha rilevato attività anomale su una o più unità di storage, viene visualizzato un messaggio sotto *Avvisi*.

. Selezionare il messaggio di avviso.
. In *Panoramica eventi*, seleziona il messaggio *Avvisi* che indica il numero di unità di archiviazione con attività anomala.
. In *Unità di archiviazione con attività anomala*, seleziona l'unità di archiviazione.
. Selezionare *Sicurezza*.
+
Se si verifica un'attività anomala sull'unità di archiviazione, viene visualizzato un messaggio in *Anti-ransomware*.

. Seleziona *Scegli un'azione*.
. Seleziona *Segnala come falso positivo* oppure *Segnala come potenziale attacco ransomware*.


.Quali sono le prossime novità?
Se sei a conoscenza di picchi di attività nella tua unità di storage, che si tratti di picchi occasionali o di un picco tipico di una nuova normalità, dovresti segnalarli come sicuri. Segnalare manualmente questi picchi come sicuri aiuta a migliorare l'accuratezza delle valutazioni delle minacce di ARP. Scopri come link:https://docs.netapp.com/us-en/ontap/anti-ransomware/manage-parameters-task.html#report-known-surges["segnala picchi noti di ARP/AI"^].
