---
sidebar: sidebar 
permalink: learn-more/software-support-limitations.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa, a50, asa a30, asa a20, asa c30, unsupported features 
summary: 'Sebbene i sistemi ASA R2 offrano un"ampia gamma di supporto per le soluzioni SAN, alcune funzionalità del software ONTAP non sono supportate.' 
---
= Supporto e limitazioni del software ONTAP per i sistemi di storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sebbene i sistemi ASA R2 offrano un'ampia gamma di supporto per le soluzioni SAN, alcune funzionalità del software ONTAP non sono supportate.

.I sistemi ASA R2 non supportano quanto segue:
* FabricPool
* Thick provisioning LUN
* MetroCluster
* NetApp Aggregate Encryption (NAE)
* Protocolli a oggetti
* API ONTAP S3 SnapMirror e S3
* SnapLock
+
SnapLock Compliance e la modalità Enterprise non sono supportate sui cluster primari negli ambienti SAN. SnapLock for SnapVault è supportato sui cluster secondari.

* La replica SnapMirror è supportata sui sistemi ASA r2 con le seguenti limitazioni:
+
** La replica sincrona SnapMirror non è supportata.
** La replica asincrona SnapMirror è supportata solo tra due sistemi ASA r2. La replica asincrona SnapMirror non è supportata tra un sistema ASA r2 e un sistema ASA, AFF o FAS o il cloud.
+
Scopri di più sulink:../data-protection/pre-defined-protection-policies.html["Criteri di replica SnapMirror supportati sui sistemi ASA r2"] .

** La sincronizzazione attiva SnapMirror è supportata solo tra due sistemi ASA r2.
+
Scopri di più sulink:../data-protection/snapmirror-active-sync.html["Sincronizzazione attiva SnapMirror sui sistemi ASA r2"] .





.I sistemi ASA R2 supportano quanto segue:
* Crittografia a doppio layer
+
I sistemi ASA r2 supportano la crittografia hardware tramite unità autocrittografanti (SED) e la crittografia software tramite la tecnologia NetApp Volume Encryption (NVE). link:../secure-data/encrypt-data-at-rest.html["Scopri come applicare la crittografia a doppio livello"] per i dati presenti sul tuo sistema ASA r2.



.Per ulteriori informazioni
* Per link:https://hwu.netapp.com/["NetApp Hardware Universe"^]ulteriori informazioni sul supporto hardware e sulle limitazioni di ASA R2, consultare la.

