---
sidebar: sidebar 
permalink: learn-more/software-support-limitations.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa, a50, asa a30, asa a20, unsupported features 
summary: 'Sebbene i sistemi ASA R2 offrano un"ampia gamma di supporto per le soluzioni SAN, alcune funzionalità del software ONTAP non sono supportate.' 
---
= Supporto e limitazioni del software ONTAP per i sistemi di storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sebbene i sistemi ASA R2 offrano un'ampia gamma di supporto per le soluzioni SAN, alcune funzionalità del software ONTAP non sono supportate.

.I sistemi ASA R2 non supportano quanto segue:
* Failover automatico della LIF iSCSI di default
+
Nei sistemi ASA R2, la LIF di networking predefinita è condivisa tra host NVMe e SCSI, quindi non supporta il failover automatico. Per attivare il failover automatico della LIF iSCSI, è necessario link:../administer/manage-client-vm-access.html#create-a-lif-network-interface["Crea una LIF solo iSCSI"]. Il failover automatico è attivato per impostazione predefinita solo su iSCSI LIFS.

+
Quando è abilitato il failover automatico di LIF iSCSI, in caso di failover dello storage, la LIF iSCSI viene automaticamente migrata dal nodo home o dalla porta al nodo partner di ha o alla porta, per poi tornare indietro una volta completato il failover. Oppure, se la porta di una LIF iSCSI diventa guasta, la LIF viene migrata automaticamente a una porta funzionante nel suo nodo home corrente e quindi nuovamente alla porta originale una volta che la porta è nuovamente funzionante.

* FabricPool
* Thick provisioning LUN
* MetroCluster
* Protocolli a oggetti
* API ONTAP S3 SnapMirror e S3
* SnapMirror (asincrono e sincrono) al cloud
* Da SnapMirror (asincrono e sincrono) a sistemi R2 non ASA


.I sistemi ASA R2 supportano quanto segue:
* SnapLock
+
link:../secure-data/ransomware-protection.html["Informazioni su come bloccare le istantanee"] Sul sistema ASA R2.

* Crittografia a doppio layer
+
link:../secure-data/encrypt-data-at-rest.html["Scopri come applicare la crittografia a doppio livello"] Ai dati sul sistema ASA R2.



.Per ulteriori informazioni
* Per link:https://hwu.netapp.com/["NetApp Hardware Universe"^]ulteriori informazioni sul supporto hardware e sulle limitazioni di ASA R2, consultare la.

