---
sidebar: sidebar 
permalink: manage-data/create-host-groups.html 
keywords: create host group, map storage units, host access, asa r2 
summary: 'Crea gruppi host per fornire agli host l"accesso alle unità di archiviazione e gestire in modo efficace le mappature di archiviazione.' 
---
= Crea gruppi host sul tuo sistema ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Su un sistema ASA r2, un _gruppo host_ è il meccanismo utilizzato per consentire agli host di accedere alle unità di storage. Un gruppo host si riferisce a un igroup per gli host SCSI o a un sottosistema NVMe per gli host NVMe. Un host può vedere solo le unità di storage mappate ai gruppi host a cui appartiene. Quando un gruppo host viene mappato a un'unità di storage, gli host membri del gruppo possono montare (creare directory e strutture di file su) l'unità di storage.

I gruppi host vengono creati automaticamente o manualmente quando crei le tue unità di archiviazione. Puoi facoltativamente seguire i passaggi seguenti per creare i gruppi host prima o dopo la creazione delle unità di archiviazione.

.Fasi
. Da System Manager, selezionare *host*.
. Selezionare gli host che si desidera aggiungere al gruppo host.
+
Dopo aver selezionato il primo host, l'opzione da aggiungere a un gruppo di host viene visualizzata sopra l'elenco degli host.

. Selezionare *Aggiungi al gruppo host*.
. Cercare e selezionare il gruppo host a cui si desidera aggiungere l'host.


.Quali sono le prossime novità?
Hai creato un gruppo host e ora puoi link:provision-san-storage.html#map-the-storage-unit-to-a-host["mapparlo su un'unità di archiviazione"] .
