---
sidebar: sidebar 
permalink: manage-data/delete-host-groups.html 
keywords: delete host groups, remove host groups, igroup, nvme subsystem, asa r2 
summary: 'Eliminare i gruppi host per rimuovere l"accesso host alle unità di archiviazione sul sistema ASA r2.' 
---
= Elimina un gruppo host sul tuo sistema ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In un sistema ASA r2, un gruppo host è il meccanismo utilizzato per consentire agli host di accedere alle unità di storage. Un gruppo host si riferisce a un igroup per gli host SCSI o a un sottosistema NVMe per gli host NVMe. Un host può visualizzare solo le unità di storage mappate ai gruppi host a cui appartiene. È possibile eliminare un gruppo host se non si desidera più che gli host del gruppo abbiano accesso alle unità di storage mappate al gruppo.

.Fasi
. In System Manager, selezionare *Storage*.
. In *Mappatura host* seleziona il gruppo host che desideri eliminare.
. Selezionare *Archiviazione mappata*.
. Selezionare *Altro*; quindi selezionare *Elimina*.
. Seleziona per confermare che vuoi continuare; quindi seleziona *Elimina*.


.Quali sono le prossime novità?
Il gruppo host viene eliminato. Gli host che facevano parte del gruppo non hanno più accesso alle unità di archiviazione mappate al gruppo host.
