---
sidebar: sidebar 
permalink: manage-data/storage-limits.html 
keywords: storage limits, cluster limits, maximum lun size, maximum, nodes per cluster, storage unit size, supported protocols, asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20,asa c30 
summary: Per performance, configurazione e supporto ottimali devi conoscere i limiti di storage di ASA R2. 
---
= Limiti di archiviazione di ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per performance, configurazione e supporto ottimali devi conoscere i limiti di storage di ASA R2.

I sistemi ASA r2 supportano i seguenti limiti di archiviazione:

[cols="3"]
|===
| Limite massimo | Per coppia HA | Per cluster 


| Gruppo di coerenza | 256 | 256 


| Applicazioni aziendali | 100 | 350 


| Nodi | 2 | 12 


| Gruppi di replicazione | 50 | 50 


| Dimensione della zona di disponibilità dello storage | 2PB | 2 PB 


| Unità di stoccaggio | 10.000 | 30.000 


| Dimensioni dell'unità di stoccaggio | 128 TB | 128 TB 


| Unità di archiviazione per gruppo di coerenza | 256 | 256 


| Macchine virtuali | 800 | 1200 
|===


== Limiti per le relazioni asincrone SnapMirror

I seguenti limiti si applicano alle unità di archiviazione e ai gruppi di coerenza in una relazione di replica asincrona SnapMirror .

[cols="3"]
|===
| Limite massimo | Per coppia HA | Per cluster 


| Gruppi di coerenza | 250 | 750 


| Unità di stoccaggio | 4.000 | 6.000 
|===


== Limiti per la relazione di sincronizzazione attiva SnapMirror

I seguenti limiti si applicano alle unità di archiviazione e ai gruppi di coerenza in una relazione di replica di sincronizzazione attiva SnapMirror .  La sincronizzazione attiva SnapMirror è supportata a partire da ONTAP 9.17.1 solo su cluster a 2 nodi.

[cols="3"]
|===
| Limite massimo | Per coppia HA | Gruppi di coerenza 


| 50 | Unità di stoccaggio | 400 
|===
.Per ulteriori informazioni
Per un elenco completo dei limiti di archiviazione più recenti di ASA R2, vedere link:https://hwu.netapp.com/["NetApp Hardware Universe"^].
