---
sidebar: sidebar 
permalink: manage-data/storage-limits.html 
keywords: storage limits, cluster limits, maximum lun size, maximum, nodes per cluster, storage unit size, supported protocols, asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30 
summary: Per prestazioni, configurazione e supporto ottimali, è necessario conoscere i limiti di archiviazione ASA r2. 
---
= Determina i limiti di archiviazione del tuo sistema ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per prestazioni, configurazione e supporto ottimali, è necessario conoscere i limiti di archiviazione ASA r2.

I limiti possono variare in base al tuo sistema ASA r2 e alla tua versione di ONTAP. Consulta link:https://hwu.netapp.com/["NetApp Hardware Universe"^] per un elenco completo dei limiti più aggiornati per il tuo sistema specifico.


NOTE: I sistemi ASA r2 sono elencati in NetApp Hardware Universe sotto *Products* come piattaforme "ASA".

.Fasi
. Vai a link:https://hwu.netapp.com["NetApp Hardware Universe"^].
. Seleziona *Products*.
. In *Piattaforme*, seleziona *ASA* come tipo di sistema.
. Seleziona il tuo sistema specifico, quindi seleziona la versione di ONTAP.
. Seleziona *Mostra risultati*.


.Risultati
Vengono visualizzati i limiti supportati per il tuo sistema ASA r2 specifico e la versione di ONTAP.
