---
sidebar: sidebar 
permalink: monitor/monitor-storage.html 
keywords: monitor, storage, cluster, utilization, usage 
summary: 'Monitora l"utilizzo dello storage per assicurarti di disporre della capacità storage necessaria per gestire i carichi di lavoro attuali e futuri.' 
searchtitle: 'Monitorare l"utilizzo dello spazio utilizzando Gestione di sistema di ONTAP | ASA R2' 
---
= Monitorare l'utilizzo di cluster e unità storage sui sistemi storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
USA Gestione sistema di ONTAP per monitorare il tuo utilizzo dello storage e assicurarti di disporre della capacità di storage necessaria per gestire i carichi di lavoro attuali e futuri.



== Monitoraggio dell'utilizzo dei cluster

Monitorare regolarmente la quantità di storage consumata dal cluster per garantire che, se necessario, sia pronta ad espandere la capacità del cluster prima di esaurire lo spazio.

.Fasi
. In System Manager, selezionare *Dashboard*.
. In *capacità*, visualizzare la quantità di spazio fisico utilizzato e la quantità di spazio disponibile nel cluster.
+
Il rapporto di riduzione dei dati rappresenta la quantità di spazio risparmiato grazie all'efficienza dello storage.



.Quali sono le prossime novità?
Se lo spazio del cluster sta per esaurirsi o se non ha la capacità necessaria per soddisfare una domanda futura, è necessario pianificare l'link:../administer/increase-storage-capacity.html["aggiungere nuove unità"]utilizzo del sistema ASA R2 per aumentare la capacità di storage.



== Monitorare l'utilizzo delle zone di disponibilità dello storage

Ogni coppia ha in un sistema ASA R2 utilizza un pool di storage comune chiamato _zona di disponibilità dello storage_. La zona di disponibilità dello storage ha accesso a tutti i dischi disponibili nel sistema storage ed è visibile a entrambi i nodi nella coppia ha.

Se nel cluster sono presenti 4 o più nodi, è possibile visualizzare la quantità di spazio utilizzata dalla zona di disponibilità dello storage per ciascuna coppia ha. Questa metrica non è disponibile per i cluster a 2 nodi.

.Fasi
. In System Manager, selezionare *Cluster*, quindi selezionare *Panoramica*.
+
Viene visualizzato un riepilogo dell'utilizzo delle zone di disponibilità dello storage per ogni coppia ha nel cluster.

. Se si desiderano metriche più dettagliate, selezionare una disponibilità dello storage specifica.
+
In *Panoramica*, vengono visualizzate la capacità della zona di disponibilità dello storage, la quantità di spazio utilizzato e il rapporto di riduzione dei dati.

+
In *unità di archiviazione* viene visualizzato un elenco di tutte le unità di archiviazione nella zona di disponibilità di archiviazione.



.Quali sono le prossime novità?
Se lo spazio nella zona di disponibilità dello storage si sta esaurendo, è necessario pianificare link:../manage-data/move-storage-units.html["spostare le unità di archiviazione"]un'altra zona di disponibilità dello storage per bilanciare l'utilizzo dello storage nel cluster.



== Monitorare l'utilizzo dell'unità di archiviazione

Monitorare la quantità di storage consumata da un'unità di storage in modo da poter aumentare in maniera proattiva le dimensioni dell'unità di storage in base alle proprie esigenze di business.

.Fasi
. In System Manager, selezionare *Storage*.
. Selezionare l'unità di archiviazione che si desidera monitorare, quindi selezionare *Panoramica*.
. In *archiviazione*, visualizzare quanto segue:
+
** Dimensioni dell'unità di archiviazione
** Quantità di spazio utilizzato
** Rapporto di riduzione dei dati
+
Il rapporto di riduzione dei dati rappresenta la quantità di spazio risparmiato grazie all'efficienza dello storage

** Istantanea utilizzata
+
Lo snapshot utilizzato rappresenta la quantità di storage utilizzata dagli snapshot.





.Quali sono le prossime novità?
Se la capacità dell'unità di archiviazione è prossima, è necessario link:../manage-data/modify-storage-units.html["modificare l'unità di conservazione"]aumentarne le dimensioni.
