---
sidebar: sidebar 
permalink: administer/revert-ontap.html 
keywords: update, revert, ontap, asa r2 
summary: I ripristini del software ONTAP per i sistemi ASA r2 seguono lo stesso processo dei ripristini per gli altri sistemi ONTAP . Il ripristino di un cluster ONTAP è dispendioso. 
---
= Ripristina ONTAP sui sistemi di archiviazione ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I ripristini del software ONTAP per i sistemi ASA r2 seguono lo stesso processo dei ripristini per gli altri sistemi ONTAP .

Il ripristino di un cluster ONTAP è un'operazione che interrompe il funzionamento. Devi mettere il cluster offline per tutta la durata del ripristino. Non dovresti ripristinare un cluster di produzione senza l'assistenza del supporto tecnico. Puoi ripristinare un cluster nuovo o di test senza assistenza. Se il ripristino di un sistema nuovo o di test non riesce, oppure se si completa correttamente ma non sei soddisfatto delle prestazioni del cluster nel tuo ambiente di produzione, dovresti contattare il supporto tecnico per assistenza.

Consulta link:https://docs.netapp.com/us-en/ontap/revert/task_reverting_an_ontap_cluster.html["Ripristinare un cluster ONTAP"] per la procedura completa di ripristino.



[[revert-requirements-for-asa-r2-systems]]
== Ripristina i requisiti per i sistemi ASA r2

Alcune configurazioni del cluster ASA r2 richiedono di eseguire azioni specifiche prima di iniziare un ripristino del software ONTAP .



[[reverting-from-ontap-9-17-1]]
=== Ritorno da ONTAP 9.17.1

Se si esegue il ripristino da ONTAP 9.17.1 su un sistema ASA r2, è necessario eseguire le seguenti azioni prima di iniziare il ripristino:


NOTE: link:space-balancing.html["bilanciamento dinamico dello spazio"]è abilitato per impostazione predefinita 14 giorni dopo l'aggiornamento a ONTAP 9.17.1 o l'inizializzazione di un nuovo cluster ONTAP 9.17.1 ASA r2.  Non è possibile tornare alla versione ONTAP 9.17.1 sul sistema ASA r2 dopo aver abilitato il bilanciamento dinamico dello spazio.

[cols="2"]
|===
| Se hai... | Prima di tornare indietro dovresti... 


| Gruppi di coerenza gerarchica in una relazione di sincronizzazione attiva SnapMirror | link:../data-protection/snapmirror-active-sync-delete-relationship.html["Elimina la relazione di sincronizzazione attiva SnapMirror"]. 


| Relazioni di importazione attive | Elimina le relazioni di importazione attive. link:../install-setup/set-up-data-access.html#migrate-data-from-a-third-party-storage-system["Scopri di più sulle relazioni di importazione"]. 


| Protezione anti-ransomware abilitata | link:../secure-data/pause-resume-anti-ransomware-protection.html["Sospendi la protezione anti-ransomware"]. 
|===