---
sidebar: sidebar 
permalink: administer/upgrade-ontap.html 
keywords: update, firmware, system files, automatic updates, automated updates, asa r2, disable, 
summary: Gli aggiornamenti software ONTAP per i sistemi ASA r2 seguono lo stesso processo degli aggiornamenti per gli altri sistemi ONTAP .  Quando aggiorni il software ONTAP sul tuo sistema ASA r2, puoi sfruttare le nuove e migliorate funzionalità ONTAP . 
---
= Aggiornare ONTAP sui sistemi storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando aggiorni il software ONTAP sul tuo sistema ASA R2, potrai sfruttare le nuove e migliorate funzionalità di ONTAP che ti consentono di ridurre i costi, accelerare i carichi di lavoro critici, migliorare la sicurezza ed espandere l'ambito di protezione dei dati disponibile per la tua organizzazione.

Gli aggiornamenti del software ONTAP per i sistemi ASA r2 seguono la stessa procedura degli aggiornamenti per altri sistemi ONTAP. Si consiglia di iniziare da link:https://docs.netapp.com/us-en/ontap/upgrade/create-upgrade-plan.html["Preparazione per l'upgrade con Upgrade Advisor in Active IQ Digital Advisor o Upgrade Health Checker"].

Dopo aver preparato l'aggiornamento, si consiglia di eseguire gli aggiornamenti utilizzando link:https://docs.netapp.com/us-en/ontap/upgrade/task_upgrade_andu_sm.html["Upgrade automatizzato senza interruzioni (ANDU) da System Manager"]. ANDU sfrutta la tecnologia di failover ad alta disponibilità (ha) di ONTAP per garantire che i cluster continuino a servire i dati senza interruzioni durante l'upgrade.

Ulteriori informazioni su link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["Aggiornamenti software ONTAP"].
