---
sidebar: sidebar 
permalink: get-started/learn-about.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, learn more, learn about, get started 
summary: 'I sistemi ASA r2 (ASA A1K, A90, A70, A50, A30, A20, C30) offrono una soluzione hardware e software unificata per un"esperienza semplificata per i clienti che utilizzano solo SAN.' 
searchtitle: Scopri di più sui sistemi ASA A1K, A90, A70, A50, A30, A20 e C30 
---
= Informazioni sui sistemi di storage ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I sistemi NetApp ASA R2 forniscono una soluzione hardware e software unificata che crea un'esperienza semplificata specifica delle esigenze dei clienti SAN.

Le seguenti piattaforme ASA sono classificate come sistemi ASA R2:

* ASA A1K
* ASA A90
* ASA A70
* ASA A50
* ASA A30
* ASA A20
* ASA C30


I sistemi ASA R2 supportano tutti i protocolli SAN (iSCSI, FC, NVMe/FC, NVMe/TCP). I protocolli iSCSI, FC, NVMe/FC e NVMe/TCP supportano l'architettura Active-Active simmetrica per il multipathing, in modo che tutti i percorsi tra gli host e lo storage siano attivi/ottimizzati. I protocolli iSCSI e NVMe/TCP supportano percorsi diretti tra gli host e lo storage.

In un sistema ASA R2, il software ONTAP e System Manager sono ottimizzati per fornire il supporto per le funzionalità SAN essenziali, rimuovendo al contempo funzioni e funzioni non supportate in ambienti SAN.

I sistemi ASA R2 introducono l'utilizzo di unità di storage con gruppi di coerenza:

* Una _unità di storage_ rende disponibile lo spazio di storage per gli host SAN per le operazioni sui dati. Un'unità di storage si riferisce a un LUN per gli host SCSI o a un namespace NVMe per gli host NVMe.
* _Un gruppo di coerenza_ è un insieme di unità di archiviazione gestite come una singola unità.


I sistemi ASA r2 utilizzano unità di archiviazione con gruppi di coerenza per semplificare la gestione dell'archiviazione e la protezione dei dati.  Ad esempio, supponiamo di avere un database composto da 10 unità di archiviazione in un gruppo di coerenza e di dover eseguire il backup dell'intero database.  Invece di eseguire il backup di ogni singola unità di archiviazione, è possibile proteggere l'intero database eseguendo il backup del gruppo di coerenza.

Per proteggere i dati da attacchi dannosi come furti o ransomware, i sistemi ASA r2 supportano un gestore di chiavi integrato, crittografia a doppio livello, autenticazione a più fattori e verifica multi-amministratore. Anche gli snapshot a prova di manomissione sono supportati sui sistemi ASA r2 secondari.

I sistemi ASA r2 non supportano la miscelazione di cluster con i sistemi ASA, AFF o FAS .

.Per ulteriori informazioni
* Per ulteriori informazioni sul supporto e sulle limitazioni dei sistemi ASA R2, consultare link:https://hwu.netapp.com/["NetApp Hardware Universe"^].
* Ulteriori informazioni su link:../learn-more/hardware-comparison.html["I sistemi ASA R2 rispetto ai sistemi ASA"].
* Ulteriori informazioni su link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"].

