---
sidebar: sidebar 
permalink: data-protection/manage-consistency-groups.html 
keywords: consistency groups, snapshots, data protection, protect data, add, remove, delete, storage units, lun, namespace, increase capacity 
summary: Utilizzare gruppi di coerenza per eseguire diverse azioni contemporaneamente su più unità di storage invece di eseguire singole azioni su ciascuna unità. 
---
= Scopri di più sui gruppi di coerenza ONTAP sui sistemi di archiviazione ASA r2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un gruppo di coerenza è una raccolta di unità di archiviazione gestite come un'unica unità.  Utilizzare gruppi di coerenza per una gestione semplificata dell'archiviazione.

Ad esempio, supponiamo di avere un database composto da 10 unità di archiviazione in un gruppo di coerenza e di dover eseguire il backup dell'intero database. Invece di eseguire il backup di ogni unità di archiviazione, è possibile eseguire il backup dell'intero database semplicemente aggiungendo la protezione dei dati snapshot al gruppo di coerenza.  Anche il backup delle unità di archiviazione come gruppo coerente anziché singolarmente garantisce un backup coerente di tutte le unità, mentre il backup delle singole unità potrebbe potenzialmente creare incongruenze.

A partire da ONTAP 9.16.1, è possibile utilizzare System Manager per creare gruppi di coerenza gerarchica sul sistema ASA r2.  In una struttura gerarchica, uno o più gruppi di coerenza sono configurati come figli sotto un gruppo di coerenza padre.

I gruppi di coerenza gerarchici consentono di applicare singole policy di snapshot a ciascun gruppo di coerenza figlio e di replicare le snapshot di tutti i gruppi di coerenza figlio in un cluster remoto come una singola unità replicando l'immagine di origine. In questo modo, si semplificano la protezione e la gestione dei dati per strutture di dati complesse. Ad esempio, si supponga di creare un gruppo di coerenza di origine denominato `SVM1_app` che contiene due gruppi di coerenza child: `SVM1app_data` Per i dati dell'applicazione e `SVM1app_logs` per i log delle applicazioni. Le copie Snapshot di `SVM1app_data` vengono eseguite ogni 15 minuti e le copie Snapshot di `SVM1app_logs` vengono eseguite ogni ora. Il gruppo di coerenza di origine `SVM1_app,` dispone di una policy SnapMirror che replica le snapshot di entrambi `SVM1app_data` e `SVM1app_logs` in un cluster remoto ogni 24 ore. Il gruppo di coerenza di origine `SVM1_app` viene gestito come una singola unità e i gruppi di coerenza child vengono gestiti come unità separate.



== Gruppi di coerenza nelle relazioni di replicazione

A partire da ONTAP 9.17.1, è possibile apportare le seguenti modifiche geometriche ai gruppi di coerenza in una relazione di replica asincrona o in una relazione di sincronizzazione attiva SnapMirror senza interrompere o eliminare la relazione.  Quando si verifica una modifica geometrica nel gruppo di coerenza primario, la modifica viene replicata nel gruppo di coerenza secondario.

* link:manage-consistency-groups-add-remove-storage-units.html["Modificare le dimensioni di un'unità di archiviazione"]aggiungendo o rimuovendo unità di archiviazione.
* link:manage-hierarchical-consistency-groups.html#promote-an-existing-consistency-group-into-a-parent-consistency-group["Promuovere un singolo gruppo di coerenza"]a un gruppo di coerenza padre.
* link:manage-hierarchical-consistency-groups.html#demote-a-parent-consistency-group-to-a-single-consistency-group["Declassare un gruppo di coerenza padre"]a un singolo gruppo di coerenza.
* link:manage-hierarchical-consistency-groups.html#detach-a-child-consistency-group-from-a-parent-consistency-group["Scollegare un gruppo di coerenza figlio"]da un gruppo di coerenza padre.
* link:manage-hierarchical-consistency-groups.html#create-a-child-consistency-group["Creare un gruppo di coerenza figlio"]utilizzando un gruppo di coerenza esistente.


In ONTAP 9.16.1, è necessariolink:snapmirror-active-sync-break-relationship.html["interrompere la relazione di replicazione asincrona"] Elink:snapmirror-active-sync-delete-relationship.html["elimina la relazione di sincronizzazione attiva SnapMirror"] prima di apportare modifiche geometriche al gruppo di coerenza.
